### ISSUE TITLE
unhashable type: 'dict'

### ISSUE THREAD

**Issue by yadavayush0808** [Twingate-Labs/saml_service_provider#1] opened 2022-09-18 04:26 UTC
while executing self.do_entity_descriptor(entity_descriptor) ,it is throwing the error unhashable type: 'dict'.
Any clue on this?

**Comment by emrul** [comment] 2022-09-19 21:09
Hi @yadavayush0808 - let us look into this!

**Comment by inbalzelinger** [comment] 2022-09-20 19:21
@yadavayush0808 Ill need some more details. Could you please attach the full stack trace?
maybe also your `entity_descriptor` object

**Comment by emrul** [comment] 2022-10-18 16:30
Hi @yadavayush0808, just following up on this - are you still experiencing an issue and can you share a stack trace to assist @inbalzelinger? If we don't hear from you we will assume the issue is resolved and close the issue.

**Closed as not planned** 2022-10-24 20:24 UTC
